package org.zaproxy.addon.ptk;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.parosproxy.paros.core.scanner.Alert;
import org.zaproxy.addon.commonlib.CommonAlertTag;

/** Unit tests for {@link PtkExampleAlerts}: alert count and field verification. */
class PtkExampleAlertsTest {

    private PtkResourcesLoader.LoadedPtkResources resources;
    private List<Alert> alerts;

    @BeforeEach
    void setUp() {
        PtkResourcesLoader loader = new PtkResourcesLoader();
        resources = loader.loadAll();
        Assumptions.assumeTrue(
                resources.getZapMapping() != null, "zap-mapping.json must be loadable");
        alerts = PtkExampleAlerts.getExampleAlerts(resources);
    }

    @Test
    void getExampleAlertsReturnsExpectedCount() {
        PtkZapMapper mapper = new PtkZapMapper(resources);
        int expectedCount = 0;
        for (var def : resources.getAllModuleDefinitions()) {
            if (def.getModules() == null) continue;
            for (var module : def.getModules()) {
                if (module.getId() == null) continue;
                if (module.getRules() != null) {
                    for (var rule : module.getRules()) {
                        if (rule.getId() != null
                                && mapper.getZapAlertReference(module.getId(), rule.getId())
                                        != null) {
                            expectedCount++;
                        }
                    }
                }
                if (module.getAttacks() != null) {
                    for (var attack : module.getAttacks()) {
                        if (attack.getId() != null
                                && mapper.getZapAlertReference(module.getId(), attack.getId())
                                        != null) {
                            expectedCount++;
                        }
                    }
                }
            }
        }
        assertEquals(expectedCount, alerts.size(), "Expected one alert per mapped rule/attack");
    }

    @Test
    void getExampleAlertsNullResourcesReturnsEmptyList() {
        List<Alert> result = PtkExampleAlerts.getExampleAlerts(null);
        assertNotNull(result);
        assertTrue(result.isEmpty());
    }

    @Test
    void sastDomXssNoInnerOuterHtmlHasExpectedFields() {
        // SAST dom-xss module, first rule: no-inner-outer-html → alertRef 220000-1
        Alert alert =
                alerts.stream()
                        .filter(a -> "220000-1".equals(a.getAlertRef()))
                        .findFirst()
                        .orElse(null);
        assertNotNull(alert, "Alert 220000-1 (no-inner-outer-html) must be present");

        assertEquals(220000, alert.getPluginId());
        assertEquals("Disallow innerHTML/outerHTML assignments", alert.getName());
        assertEquals(Alert.RISK_HIGH, alert.getRisk());
        assertEquals(Alert.CONFIDENCE_MEDIUM, alert.getConfidence());
        assertEquals("https://www.example.com/", alert.getUri());
        assertEquals(79, alert.getCweId());
        assertEquals("220000-1", alert.getAlertRef());

        String description = alert.getDescription();
        assertTrue(
                description.contains(
                        "Detects cases where untrusted data from the DOM (URL, element values, storage, messages, etc.) "
                                + "flows into HTML/JS execution sinks"),
                "Description should include rule-level description");
        assertTrue(
                description.contains("Generated by OWASP PTK SAST Module"),
                "Description should end with engine attribution");

        String solution = alert.getSolution();
        assertNotNull(solution);
        assertFalse(solution.isBlank(), "Solution should not be blank");
        assertTrue(solution.contains("DOMPurify"), "Solution should mention DOMPurify");

        String reference = alert.getReference();
        assertNotNull(reference);
        assertTrue(reference.contains("owasp.org"), "Reference should include OWASP link");
        assertTrue(reference.contains("cwe.mitre.org"), "Reference should include CWE link");

        Map<String, String> tags = alert.getTags();
        assertNotNull(tags);
        assertEquals(
                CommonAlertTag.OWASP_2025_A05_INJECTION.getValue(),
                tags.get(CommonAlertTag.OWASP_2025_A05_INJECTION.getTag()));
        assertEquals(
                CommonAlertTag.OWASP_2021_A03_INJECTION.getValue(),
                tags.get(CommonAlertTag.OWASP_2021_A03_INJECTION.getTag()));
        assertEquals(PtkAlertBuilder.TAG_TOOL_PTK_URL, tags.get(PtkAlertBuilder.TAG_TOOL_PTK));

        assertTrue(alert instanceof ExampleAlert, "Alert should be an ExampleAlert");
        ExampleAlert exampleAlert = (ExampleAlert) alert;
        assertEquals("DOM-based XSS", exampleAlert.getParentAlertName());
        assertEquals(
                "https://github.com/DenisPodgurskii/pentestkit/blob/master/src/ptk/background/sast/modules/modules.json",
                exampleAlert.getCodeLink());
        assertEquals(
                "src/ptk/background/sast/modules/modules.json", exampleAlert.getCodeLinkText());
    }

    @Test
    void dastSqlInjectionSingleQuoteHasExpectedFields() {
        // DAST sql_injection module, attack sqlinjection_1 → alertRef 200000-1
        Alert alert =
                alerts.stream()
                        .filter(a -> "200000-1".equals(a.getAlertRef()))
                        .findFirst()
                        .orElse(null);
        assertNotNull(alert, "Alert 200000-1 (sqlinjection_1) must be present");

        assertEquals(200000, alert.getPluginId());
        assertEquals("SQL Injection - Single Quote (before)", alert.getName());
        assertEquals(Alert.RISK_HIGH, alert.getRisk());
        assertEquals(Alert.CONFIDENCE_MEDIUM, alert.getConfidence());
        assertEquals("https://www.example.com/", alert.getUri());
        assertEquals(89, alert.getCweId());
        assertEquals("200000-1", alert.getAlertRef());

        String description = alert.getDescription();
        assertTrue(
                description.contains("SQL injection attack"),
                "Description should include module-level SQL injection description");
        assertTrue(
                description.contains("Generated by OWASP PTK DAST Module"),
                "Description should include engine attribution");

        String solution = alert.getSolution();
        assertNotNull(solution);
        assertTrue(
                solution.contains("parameterized queries"),
                "Solution should mention parameterized queries");

        String reference = alert.getReference();
        assertNotNull(reference);
        assertTrue(reference.contains("owasp.org"), "Reference should include OWASP link");
        assertTrue(reference.contains("cwe.mitre.org"), "Reference should include CWE link");

        Map<String, String> tags = alert.getTags();
        assertNotNull(tags);
        assertEquals(
                CommonAlertTag.OWASP_2025_A05_INJECTION.getValue(),
                tags.get(CommonAlertTag.OWASP_2025_A05_INJECTION.getTag()));
        assertEquals(
                CommonAlertTag.OWASP_2021_A03_INJECTION.getValue(),
                tags.get(CommonAlertTag.OWASP_2021_A03_INJECTION.getTag()));
        assertEquals(PtkAlertBuilder.TAG_TOOL_PTK_URL, tags.get(PtkAlertBuilder.TAG_TOOL_PTK));

        assertTrue(alert instanceof ExampleAlert, "Alert should be an ExampleAlert");
        ExampleAlert exampleAlert = (ExampleAlert) alert;
        assertEquals("SQL Injection", exampleAlert.getParentAlertName());
        assertEquals(
                "https://github.com/DenisPodgurskii/pentestkit/blob/master/src/ptk/background/dast/modules/modules.json",
                exampleAlert.getCodeLink());
        assertEquals(
                "src/ptk/background/dast/modules/modules.json", exampleAlert.getCodeLinkText());
    }
}
