package org.zaproxy.addon.ptk;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.reflect.TypeToken;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.parosproxy.paros.core.scanner.Alert;
import org.zaproxy.addon.commonlib.CommonAlertTag;
import org.zaproxy.addon.ptk.model.PtkAttack;
import org.zaproxy.addon.ptk.model.PtkFinding;
import org.zaproxy.addon.ptk.model.PtkFindingSourceSink;
import org.zaproxy.addon.ptk.model.PtkModule;
import org.zaproxy.addon.ptk.model.PtkModuleMetadata;
import org.zaproxy.addon.ptk.model.PtkModulesDefinition;
import org.zaproxy.addon.ptk.model.PtkRule;

/**
 * Builds ZAP alerts from PTK findings. Reuses logic from {@link PtkExampleAlerts} for severity,
 * CWE, OWASP tags, and HTML-to-plain-text conversion. Merges dynamic data from PTK findings with
 * static metadata from module definitions.
 */
public final class PtkAlertBuilder {

    private static final Pattern CWE_PATTERN = Pattern.compile("CWE-(\\d+)");
    private static final Pattern OWASP_PTK_PATTERN = Pattern.compile("A(\\d{1,2}):(\\d{4})");
    private static final Gson GSON = new Gson();

    static final String EXAMPLE_URI = "https://www.example.com/";
    private static final String CODE_LINK_BASE =
            "https://github.com/DenisPodgurskii/pentestkit/blob/master/src/ptk/background/";
    private static final String CODE_LINK_SUFFIX = "/modules/modules.json";
    private static final String CODE_LINK_TEXT_PREFIX = "src/ptk/background/";

    /** Tag linking PTK alerts to the add-on documentation. */
    public static final String TAG_TOOL_PTK = "TOOL_PTK";

    /** URL for the TOOL_PTK tag. */
    public static final String TAG_TOOL_PTK_URL =
            "https://www.zaproxy.org/docs/desktop/addons/owasp-ptk/";

    private static final Map<String, String> OWASP_TAG_URLS =
            Stream.of(CommonAlertTag.values())
                    .filter(t -> t.getTag().startsWith("OWASP_"))
                    .collect(
                            Collectors.toUnmodifiableMap(
                                    CommonAlertTag::getTag, CommonAlertTag::getValue));

    private PtkAlertBuilder() {}

    /**
     * Builds an example alert from PTK module/rule metadata for use in {@link
     * ExampleAlertProvider}.
     *
     * @param alertRef the ZAP alert reference (e.g. "220000-1")
     * @param engine engine name (SAST, IAST, DAST)
     * @param moduleName display name of the module
     * @param ruleOrAttackName display name of the rule or attack
     * @param meta parsed module metadata (description, CWE, OWASP, etc.)
     * @param ruleSeverity rule-level severity override, or null to fall back to module severity
     * @param ruleDescription rule-level description override, or null to fall back to module
     *     description
     * @return the built ExampleAlert, or null if the alertRef is invalid
     */
    static ExampleAlert buildExampleAlert(
            String alertRef,
            String engine,
            String moduleName,
            String ruleOrAttackName,
            PtkModuleMetadata meta,
            String ruleSeverity,
            String ruleDescription) {
        int pluginId = parseBaseAlertId(alertRef);
        if (pluginId < 0) {
            return null;
        }
        int risk = parseSeverity(ruleSeverity != null ? ruleSeverity : getSeverity(meta));
        String description =
                htmlToPlainText(ruleDescription != null ? ruleDescription : getDescription(meta));
        if (description == null || description.isEmpty()) {
            description = "PTK " + engine + " finding";
        }
        description += "\n\nGenerated by OWASP PTK " + engine + " Module";
        String solution = htmlToPlainText(getRecommendation(meta));
        String reference = formatReferences(meta);
        int cweId = parseFirstCwe(meta);
        Map<String, String> tags = owaspToZapTags(meta);
        tags.put(TAG_TOOL_PTK, TAG_TOOL_PTK_URL);

        Alert.Builder builder =
                Alert.builder()
                        .setPluginId(pluginId)
                        .setName(ruleOrAttackName)
                        .setRisk(risk)
                        .setConfidence(Alert.CONFIDENCE_MEDIUM)
                        .setDescription(description)
                        .setSolution(solution != null ? solution : "")
                        .setReference(reference != null ? reference : "")
                        .setCweId(cweId)
                        .setUri(EXAMPLE_URI)
                        .setAlertRef(alertRef);
        builder.setTags(tags);
        Alert baseAlert = builder.build();
        String engineLower = engine.toLowerCase(Locale.ROOT);
        String codeLink = CODE_LINK_BASE + engineLower + CODE_LINK_SUFFIX;
        String codeLinkText = CODE_LINK_TEXT_PREFIX + engineLower + CODE_LINK_SUFFIX;
        return new ExampleAlert(baseAlert, moduleName, codeLink, codeLinkText);
    }

    /**
     * Builds a ZAP alert from a PTK finding. Uses the mapper for alert reference; merges finding
     * data (summary, severity, location, proof) with module metadata (description, solution, CWE)
     * when available.
     *
     * @param finding the PTK finding
     * @param engine engine name (SAST, IAST, DAST)
     * @param mapper PTK-to-ZAP mapper
     * @param resources loaded PTK resources for module metadata
     * @return built Alert, or null if finding is not mapped
     */
    public static Alert buildFromFinding(
            PtkFinding finding,
            String engine,
            PtkZapMapper mapper,
            PtkResourcesLoader.LoadedPtkResources resources) {
        String alertRef = mapper.getZapAlertReference(finding.getModuleId(), finding.getRuleId());
        if (alertRef == null) {
            return null;
        }
        int pluginId = parseBaseAlertId(alertRef);
        if (pluginId < 0) {
            return null;
        }

        ModuleRuleInfo info =
                findModuleRuleOrAttack(
                        finding.getModuleId(),
                        finding.getRuleId(),
                        finding.getAttackId(),
                        resources);
        if (info == null) return null;
        PtkModuleMetadata meta = info.meta;
        String ruleName = getDisplayName(info);
        String severity = finding.getSeverity();
        if (severity == null && info.rule != null && info.rule.getSeverity() != null) {
            severity = info.rule.getSeverity();
        }
        if (severity == null) severity = getSeverity(meta);
        int risk = parseSeverity(severity);
        int confidence = parseConfidence(finding.getConfidence());

        String description = buildDescription(info, engine);
        String solution = htmlToPlainText(getRecommendation(meta));
        String reference = formatReferences(meta);
        int cweId = parseFirstCwe(meta);
        Map<String, String> tags = owaspToZapTags(meta);
        tags.put(TAG_TOOL_PTK, TAG_TOOL_PTK_URL);

        String uri = finding.getUri() != null ? finding.getUri() : "about:blank";
        String param = finding.getParam();
        String attack = buildAttack(finding);
        String evidence = buildEvidence(finding);
        String otherInfo = buildOtherInfo(finding);
        String inputVector = buildInputVector(finding, engine);

        Alert.Builder builder =
                Alert.builder()
                        .setPluginId(pluginId)
                        .setName(ruleName)
                        .setRisk(risk)
                        .setConfidence(confidence)
                        .setDescription(description)
                        .setSolution(solution != null ? solution : "")
                        .setReference(reference != null ? reference : "")
                        .setCweId(cweId)
                        .setUri(uri)
                        .setParam(param != null ? param : "")
                        .setAttack(attack != null ? attack : "")
                        .setEvidence(evidence != null ? evidence : "")
                        .setOtherInfo(otherInfo != null ? otherInfo : "")
                        .setAlertRef(alertRef);
        if (inputVector != null && !inputVector.isBlank()) {
            builder.setInputVector(inputVector);
        }
        builder.setTags(tags);
        return builder.build();
    }

    private static final class ModuleRuleInfo {
        final PtkModule module;
        final PtkRule rule;
        final PtkAttack attack;
        final PtkModuleMetadata meta;

        ModuleRuleInfo(PtkModule module, PtkRule rule, PtkAttack attack, PtkModuleMetadata meta) {
            this.module = module;
            this.rule = rule;
            this.attack = attack;
            this.meta = meta;
        }
    }

    private static ModuleRuleInfo findModuleRuleOrAttack(
            String moduleId,
            String ruleId,
            String attackId,
            PtkResourcesLoader.LoadedPtkResources resources) {
        if (resources == null || moduleId == null) return null;
        String lookupId = ruleId != null ? ruleId : attackId;
        if (lookupId == null) return null;
        for (PtkModulesDefinition def : resources.getAllModuleDefinitions()) {
            if (def.getModules() == null) continue;
            for (PtkModule m : def.getModules()) {
                if (!moduleId.equals(m.getId())) continue;
                PtkModuleMetadata meta = parseModuleMetadata(m.getMetadata());
                if (m.getRules() != null) {
                    for (PtkRule r : m.getRules()) {
                        if (lookupId.equals(r.getId())) {
                            return new ModuleRuleInfo(m, r, null, meta);
                        }
                    }
                }
                if (m.getAttacks() != null) {
                    for (PtkAttack a : m.getAttacks()) {
                        if (lookupId.equals(a.getId())) {
                            return new ModuleRuleInfo(m, null, a, meta);
                        }
                    }
                }
                return new ModuleRuleInfo(m, null, null, meta);
            }
        }
        return null;
    }

    static PtkModuleMetadata parseModuleMetadata(JsonElement metadata) {
        if (metadata == null || !metadata.isJsonObject()) return null;
        JsonObject obj = metadata.getAsJsonObject();
        PtkModuleMetadata meta = new PtkModuleMetadata();
        if (obj.has("taxonomy")) {
            JsonObject tax = obj.getAsJsonObject("taxonomy");
            if (tax.has("severity")) meta.setSeverity(tax.get("severity").getAsString());
            if (tax.has("category")) meta.setCategory(tax.get("category").getAsString());
            if (tax.has("owasp"))
                meta.setOwasp(
                        GSON.fromJson(
                                tax.get("owasp"), new TypeToken<List<String>>() {}.getType()));
            if (tax.has("cwe"))
                meta.setCwe(
                        GSON.fromJson(tax.get("cwe"), new TypeToken<List<String>>() {}.getType()));
            if (tax.has("tags"))
                meta.setTags(
                        GSON.fromJson(tax.get("tags"), new TypeToken<List<String>>() {}.getType()));
        }
        if (obj.has("docs")) {
            JsonObject docs = obj.getAsJsonObject("docs");
            if (docs.has("description")) meta.setDescription(docs.get("description").getAsString());
            if (docs.has("recommendation"))
                meta.setRecommendation(docs.get("recommendation").getAsString());
            if (docs.has("links"))
                meta.setLinks(
                        GSON.fromJson(
                                docs.get("links"),
                                new TypeToken<Map<String, String>>() {}.getType()));
        }
        if (meta.getDescription() == null
                && meta.getRecommendation() == null
                && meta.getLinks() == null
                && meta.getOwasp() == null
                && meta.getCwe() == null
                && meta.getSeverity() == null) {
            meta = GSON.fromJson(metadata, PtkModuleMetadata.class);
        }
        return meta;
    }

    private static String getDisplayName(ModuleRuleInfo info) {
        if (info.rule != null && info.rule.getName() != null && !info.rule.getName().isBlank()) {
            return info.rule.getName();
        }
        if (info.attack != null
                && info.attack.getName() != null
                && !info.attack.getName().isBlank()) {
            return info.attack.getName();
        }
        if (info.module != null
                && info.module.getName() != null
                && !info.module.getName().isBlank()) {
            return info.module.getName();
        }
        String id =
                info.rule != null
                        ? info.rule.getId()
                        : info.attack != null
                                ? info.attack.getId()
                                : info.module != null ? info.module.getId() : null;
        return id != null ? id : "PTK Finding";
    }

    private static String buildDescription(ModuleRuleInfo info, String engine) {
        String fromRule = info.rule != null ? parseRuleDescription(info.rule.getMetadata()) : null;
        String fromAttack =
                info.attack != null ? parseRuleDescription(info.attack.getMetadata()) : null;
        String fromMeta = getDescription(info.meta);
        String base =
                htmlToPlainText(
                        fromRule != null ? fromRule : fromAttack != null ? fromAttack : fromMeta);
        if (base == null || base.isEmpty()) base = "PTK finding";
        return base + "\n\nGenerated by OWASP PTK " + engine + " Module";
    }

    static String parseRuleDescription(JsonElement metadata) {
        if (metadata == null
                || !metadata.isJsonObject()
                || metadata.getAsJsonObject().get("description") == null) {
            return null;
        }
        JsonElement desc = metadata.getAsJsonObject().get("description");
        return desc.isJsonNull() ? null : desc.getAsString();
    }

    private static String buildInputVector(PtkFinding finding, String engine) {
        String sourceStr = getSourceString(finding.getSource());
        if (finding.getSource() == null && finding.getParam() != null) {
            sourceStr = finding.getParam();
        }
        String enginePart = engine != null && !engine.isBlank() ? engine : "";
        String sourcePart = sourceStr != null && !sourceStr.isBlank() ? sourceStr : "";
        StringBuilder sb = new StringBuilder("PTK");
        if (!enginePart.isEmpty()) sb.append(" ").append(enginePart);
        if (!sourcePart.isEmpty()) sb.append(" ").append(sourcePart);
        return sb.toString();
    }

    private static String getSourceString(PtkFindingSourceSink source) {
        if (source == null) return null;
        if (source.getLabel() != null && !source.getLabel().isBlank()) {
            return source.getLabel();
        }
        if (source.getKind() != null && !source.getKind().isBlank()) {
            return source.getKind();
        }
        if (source.getFile() != null && source.getLine() != null) {
            return source.getFile() + ":" + source.getLine();
        }
        if (source.getId() != null && !source.getId().isBlank()) {
            return source.getId();
        }
        return null;
    }

    private static String buildAttack(PtkFinding finding) {
        if (finding.getProof() != null && finding.getProof().getPayload() != null) {
            return finding.getProof().getPayload();
        }
        return null;
    }

    private static String buildEvidence(PtkFinding finding) {
        if (finding.getProof() != null && finding.getProof().getProof() != null) {
            return finding.getProof().getProof();
        }
        return null;
    }

    private static String buildOtherInfo(PtkFinding finding) {
        StringBuilder sb = new StringBuilder();
        if (finding.getSummary() != null && !finding.getSummary().isBlank()) {
            sb.append("Summary: ").append(finding.getSummary());
        }
        if (finding.getSource() != null && finding.getSource().getLabel() != null) {
            if (sb.length() > 0) sb.append("\n");
            sb.append("Source: ").append(finding.getSource().getLabel());
        }
        if (finding.getSink() != null && finding.getSink().getLabel() != null) {
            if (sb.length() > 0) sb.append("\n");
            sb.append("Sink: ").append(finding.getSink().getLabel());
        }
        if (finding.getCodeSnippet() != null && !finding.getCodeSnippet().isEmpty()) {
            if (sb.length() > 0) sb.append("\n\n");
            sb.append("Code: ").append(truncate(finding.getCodeSnippet(), 500));
        }
        if (finding.getContext() != null) {
            if (finding.getContext().getDomPath() != null) {
                if (sb.length() > 0) sb.append("\n");
                sb.append("DOM: ").append(finding.getContext().getDomPath());
            }
        }
        return sb.length() > 0 ? sb.toString() : null;
    }

    private static String truncate(String s, int max) {
        if (s == null || s.length() <= max) return s;
        return s.substring(0, max) + "...";
    }

    static int parseBaseAlertId(String alertRef) {
        if (alertRef == null) return -1;
        int idx = alertRef.indexOf('-');
        if (idx <= 0) return -1;
        try {
            return Integer.parseInt(alertRef.substring(0, idx));
        } catch (NumberFormatException e) {
            return -1;
        }
    }

    static int parseSeverity(String severity) {
        if (severity == null) return Alert.RISK_MEDIUM;
        switch (severity.toLowerCase(Locale.ROOT)) {
            case "high":
                return Alert.RISK_HIGH;
            case "medium":
                return Alert.RISK_MEDIUM;
            case "low":
                return Alert.RISK_LOW;
            case "info":
                return Alert.RISK_INFO;
            default:
                return Alert.RISK_MEDIUM;
        }
    }

    private static int parseConfidence(Integer confidence) {
        if (confidence == null) return Alert.CONFIDENCE_MEDIUM;
        if (confidence >= 80) return Alert.CONFIDENCE_HIGH;
        if (confidence >= 60) return Alert.CONFIDENCE_MEDIUM;
        if (confidence >= 40) return Alert.CONFIDENCE_LOW;
        return Alert.CONFIDENCE_LOW;
    }

    static int parseFirstCwe(PtkModuleMetadata meta) {
        if (meta == null || meta.getCwe() == null || meta.getCwe().isEmpty()) return -1;
        for (String cwe : meta.getCwe()) {
            Matcher m = CWE_PATTERN.matcher(cwe);
            if (m.find()) {
                try {
                    return Integer.parseInt(m.group(1));
                } catch (NumberFormatException ignored) {
                    // continue
                }
            }
        }
        return -1;
    }

    private static String getSeverity(PtkModuleMetadata meta) {
        return meta != null && meta.getSeverity() != null ? meta.getSeverity() : "medium";
    }

    private static String getDescription(PtkModuleMetadata meta) {
        return meta != null ? meta.getDescription() : null;
    }

    private static String getRecommendation(PtkModuleMetadata meta) {
        return meta != null ? meta.getRecommendation() : null;
    }

    static Map<String, String> owaspToZapTags(PtkModuleMetadata meta) {
        Map<String, String> tags = new LinkedHashMap<>();
        if (meta == null || meta.getOwasp() == null) {
            return tags;
        }
        for (String ptkOwasp : meta.getOwasp()) {
            if (ptkOwasp == null) {
                continue;
            }
            Matcher m = OWASP_PTK_PATTERN.matcher(ptkOwasp);
            if (m.find()) {
                String num = m.group(1);
                String year = m.group(2);
                String zapTag = "OWASP_" + year + "_A" + (num.length() == 1 ? "0" + num : num);
                tags.put(zapTag, OWASP_TAG_URLS.getOrDefault(zapTag, ""));
            }
        }
        return tags;
    }

    static String formatReferences(PtkModuleMetadata meta) {
        if (meta == null || meta.getLinks() == null || meta.getLinks().isEmpty()) return null;
        StringBuilder sb = new StringBuilder();
        for (String url : meta.getLinks().values()) {
            if (url == null) continue;
            int httpIdx = url.indexOf("http");
            if (httpIdx >= 0) url = url.substring(httpIdx);
            if (sb.length() > 0) sb.append("\n");
            sb.append(url);
        }
        return sb.toString();
    }

    static String htmlToPlainText(String html) {
        if (html == null || html.isEmpty()) return html;
        String s = html;
        s = s.replaceAll("(?i)</p>", "\n");
        s = s.replaceAll("(?i)<p\\s[^>]*>", "\n");
        s = s.replaceAll("(?i)<p>", "\n");
        s = s.replaceAll("(?i)</div>", "\n");
        s = s.replaceAll("(?i)<div\\s[^>]*>", "\n");
        s = s.replaceAll("(?i)<div>", "\n");
        s = s.replaceAll("(?i)</ul>", "\n");
        s = s.replaceAll("(?i)<ul[^>]*>", "\n");
        s = s.replaceAll("(?i)</ol>", "\n");
        s = s.replaceAll("(?i)<ol[^>]*>", "\n");
        s = s.replaceAll("(?i)<li\\s[^>]*>", "\n• ");
        s = s.replaceAll("(?i)<li>", "\n• ");
        s = s.replaceAll("(?i)</li>", "");
        s = s.replaceAll("(?i)<br\\s*/?>", "\n");
        s = s.replaceAll("<[^>]+>", "");
        s = s.replace("&nbsp;", " ");
        s = s.replace("&lt;", "<");
        s = s.replace("&gt;", ">");
        s = s.replace("&amp;", "&");
        s = s.replace("&quot;", "\"");
        s = s.replace("&#39;", "'");
        s = s.replace("&apos;", "'");
        s = s.replaceAll("[ \t]+", " ");
        s = s.replaceAll("\n[ \t]+", "\n");
        s = s.replaceAll("[ \t]+\n", "\n");
        s = s.replaceAll("\n{3,}", "\n\n");
        return s.trim();
    }
}
